[project]
name = "fastapi-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "riyabote237-ui", email = "riyabote237@gmail.com" }
    { name = "Apsara Shrestha", email = "apsarashrestha651@gmail.com" }
    { name = "arnimabasnet32-a11y", email = "arnimabasnet32@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pymysql>=1.2.0",
    "sqlmodel>=0.0.39",
]

[project.scripts]
fastapi-demo = "fastapi_demo:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
